# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: x.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='x.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x07x.proto\"&\n\x08head_msg\x12\x0c\n\x04size\x18\x01 \x01(\x0f\x12\x0c\n\x04type\x18\x02 \x01(\x07\"%\n\x02on\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x0e\n\x06passwd\x18\x02 \x01(\t\"\x14\n\x04info\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x05\n\x03off*/\n\x06ts_cmd\x12\n\n\x06\x43MD_ON\x10\x00\x12\x0c\n\x08\x43MD_INFO\x10\x01\x12\x0b\n\x07\x43MD_OFF\x10\x02\x62\x06proto3')
)

_TS_CMD = _descriptor.EnumDescriptor(
  name='ts_cmd',
  full_name='ts_cmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_ON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_INFO', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_OFF', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=119,
  serialized_end=166,
)
_sym_db.RegisterEnumDescriptor(_TS_CMD)

ts_cmd = enum_type_wrapper.EnumTypeWrapper(_TS_CMD)
CMD_ON = 0
CMD_INFO = 1
CMD_OFF = 2



_HEAD_MSG = _descriptor.Descriptor(
  name='head_msg',
  full_name='head_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='head_msg.size', index=0,
      number=1, type=15, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='head_msg.type', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=11,
  serialized_end=49,
)


_ON = _descriptor.Descriptor(
  name='on',
  full_name='on',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='on.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='passwd', full_name='on.passwd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=88,
)


_INFO = _descriptor.Descriptor(
  name='info',
  full_name='info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='info.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=110,
)


_OFF = _descriptor.Descriptor(
  name='off',
  full_name='off',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['head_msg'] = _HEAD_MSG
DESCRIPTOR.message_types_by_name['on'] = _ON
DESCRIPTOR.message_types_by_name['info'] = _INFO
DESCRIPTOR.message_types_by_name['off'] = _OFF
DESCRIPTOR.enum_types_by_name['ts_cmd'] = _TS_CMD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

head_msg = _reflection.GeneratedProtocolMessageType('head_msg', (_message.Message,), dict(
  DESCRIPTOR = _HEAD_MSG,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:head_msg)
  ))
_sym_db.RegisterMessage(head_msg)

on = _reflection.GeneratedProtocolMessageType('on', (_message.Message,), dict(
  DESCRIPTOR = _ON,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:on)
  ))
_sym_db.RegisterMessage(on)

info = _reflection.GeneratedProtocolMessageType('info', (_message.Message,), dict(
  DESCRIPTOR = _INFO,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:info)
  ))
_sym_db.RegisterMessage(info)

off = _reflection.GeneratedProtocolMessageType('off', (_message.Message,), dict(
  DESCRIPTOR = _OFF,
  __module__ = 'x_pb2'
  # @@protoc_insertion_point(class_scope:off)
  ))
_sym_db.RegisterMessage(off)


# @@protoc_insertion_point(module_scope)
